# This is the config that worked before
lsi: false
safe: true
#source: jbrandon99.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge 
url: "https://jbrandon99.github.io"
baseurl: ""
header_title: "Palestine Books in Libraries"
header_subtitle: "  "
seo_description: ""
colour_scheme: ""
font_scheme: ""
one_page_site: ""
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
collections:
  pages:
    output: true
    permalink: /:name          
    source: _pages 
  posts:
    output: true
    permalink: /blog/:name          
    source: _posts  
  locations:
    output: true
    permalink: /locations/:title/  
    source: _locations              
defaults:
  - scope:
      path: "_pages"
    values:
      layout: default